### ISSUE TITLE
Authorizing Subsequent API requests

### ISSUE THREAD

**Issue by mdwiltfong** [DigoBaiocchi/ecommerceAPI#3]
Hey Digo!

Love where this is going! I thought I would write down what we spoke about today during the meet up! 

Typically, Passport stores the id of a session in a table in your db. It then hashes this id, and then sends it to the browser with the instruction to store it as a cookie, as well as to send it with any subsequent http requests. 

Because Mocha doesn't have a browser environment, you will have to be specific in sending the session id along with any of the subsequent requests. 

Let me know how this goes!

**Comment by DigoBaiocchi** [comment]
Hey Michael!

I think I got what you are talking about. I added a before function before the tests to log the user in and store the header 'set-cookie' in a variable once the user is logged in like this:

```javascript
let cookie;

before((done) => {
    request(app)
    .post('/auth/login/')
    .send(userData)
    .end((err, res) => {
        if (err) return done(err);
        cookie = res.headers['set-cookie']
        done();
    })
});
```

Then I passed the cookie variable in the tests like this:

```javascript
    it('responses with 201 when product was added to the cart', (done) => {
        request(app)
            .post(path)
            .set('Cookie', cookie) // <---- here
            .send(data)
            .set('accept', 'application/json')
            .expect('Content-Type', /json/)
            .expect(201)
            .expect({ "message": `Product ${data["productId"]} was added to cart table`})
            .end((err) => {
                if (err) return done(err);
                done();
            })
    });
```

And it worked!

Thanks a lot for all your help yesterday and for sending this over now! I've been enjoying and learning so much in the Wednesday sessions.
